### ISSUE TITLE
Yarn start ?

### ISSUE THREAD

**Issue by juschief** [ethereum-boilerplate/ethereum-boilerplate#194]
getting this error when trying to run boiler plate 

PS C:\Users\sagen\Ebp\ethereum-boilerplate> yarn run start     
yarn run v1.22.19
warning ..\..\package.json: License should be a valid SPDX license expression
$ next start
'next' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

**Comment by Y0moo** [comment]
Hi @juschief !

Have you installed all dependencies by "yarn install"?

**Comment by stevegyutyan** [comment]
Delete node modules and lock files
re install dependencies.

**Comment by juschief** [comment]
yea I did delete lock files and installed dependencies.  Got it too work with npm run build and then npm start.  I deleted the yarn lock file and yarn install (reinstalled) dependencies before i did this but, yea it worked.  When i ran yarn start it told me Error: Could not find a production build in the 'C:\Users\13478\Desktop\Boilerplate\ethereum-boilerplate\.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (C:\Users\13478\Desktop\Boilerplate\ethereum-boilerplate\node_modules\next\dist\server\next-server.js:171:23)
    at new Server (C:\Users\13478\Desktop\Boilerplate\ethereum-boilerplate\node_modules\next\dist\server\base-server.js:58:29)
    at new NextNodeServer (C:\Users\13478\Desktop\Boilerplate\ethereum-boilerplate\node_modules\next\dist\server\next-server.js:68:9)
    at NextServer.createServer (C:\Users\13478\Desktop\Boilerplate\ethereum-boilerplate\node_modules\next\dist\server\next.js:143:16)
    at async C:\Users\13478\Desktop\Boilerplate\ethereum-boilerplate\node_modules\next\dist\server\next.js:155:31
    at async NextServer.prepare (C:\Users\13478\Desktop\Boilerplate\ethereum-boilerplate\node_modules\next\dist\server\next.js:130:24)
    at async C:\Users\13478\Desktop\Boilerplate\ethereum-boilerplate\node_modules\next\dist\cli\next-start.js:116:9
error Command failed with exit code 1.
